
--  script completo ORACLE  (mishel loeiza)--

CREATE TABLESPACE PROYECTO_BDMISHEL
 DATAFILE 'PROYECTO_BDMISHEL_XEPDB1.dbf'
 SIZE 50M
 AUTOEXTEND ON
 NEXT 10M MAXSIZE UNLIMITED;

CREATE USER biblioteca IDENTIFIED BY biblioteca123
DEFAULT TABLESPACE PROYECTO_BDMISHEL
QUOTA UNLIMITED ON PROYECTO_BDMISHEL;

GRANT CONNECT, RESOURCE TO biblioteca; --termina sesion

CONNECT SYSTEM/12345@localhost:1521/XEPDB1 --inicia en el GENERAL PARA VER SU EXISTENCIA

SELECT username FROM all_users WHERE username = 'BIBLIOTECA';--MUESTRA SI SE CREÒ

--CONECTAMOS A BLIOTECA CREADO
CONNECT biblioteca/biblioteca123@localhost:1521/XEPDB1
  
  --CREACIÒN DE TABLAS

-- Tabla de usuarios
CREATE TABLE usuario (
  id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(60) NOT NULL,
  password VARCHAR2(255) NOT NULL
);


-- Tabla de permisos por usuario
CREATE TABLE permisos_usuario (
  id_usuario NUMBER(11) PRIMARY KEY,
  puede_mantenimiento NUMBER(1) DEFAULT 0,
  puede_procesos NUMBER(1) DEFAULT 0,
  puede_eliminar NUMBER(1) DEFAULT 0,
  puede_registrar NUMBER(1) DEFAULT 0,
  puede_modificar NUMBER(1) DEFAULT 0,
  APL103 NUMBER(1) DEFAULT 0,
  APL104 NUMBER(1) DEFAULT 0,
  APL105 NUMBER(1) DEFAULT 0,
  APL106 NUMBER(1) DEFAULT 0,
  APL107 NUMBER(1) DEFAULT 0,
  APL108 NUMBER(1) DEFAULT 0,
  APL109 NUMBER(1) DEFAULT 0,
  APL110 NUMBER(1) DEFAULT 0,
  APL111 NUMBER(1) DEFAULT 0,
  APL112 NUMBER(1) DEFAULT 0,
  CONSTRAINT fk_permisos_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Tabla de libros
CREATE TABLE libro (
  id_libro NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  titulo VARCHAR2(255) NOT NULL,
  autor VARCHAR2(100),
  editorial VARCHAR2(255),
  categoria VARCHAR2(100),
  stock NUMBER(11) NOT NULL,
  estado VARCHAR2(20) DEFAULT 'activo' NOT NULL
);

-- Tabla de préstamos
CREATE TABLE prestamo (
  id_prestamo NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_libro NUMBER(11) NOT NULL,
  id_usuario NUMBER(11) NOT NULL,
  fecha_prestamo TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  estado VARCHAR2(20) DEFAULT 'activo' NOT NULL,
  CONSTRAINT fk_prestamo_libro FOREIGN KEY (id_libro) REFERENCES libro(id_libro),
  CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

-- Tabla de devoluciones
CREATE TABLE devolucion (
  id_devolucion NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_prestamo NUMBER(11) NOT NULL,
  fecha_devolucion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  observaciones VARCHAR2(255),
  CONSTRAINT fk_devolucion_prestamo FOREIGN KEY (id_prestamo) REFERENCES prestamo(id_prestamo)
);

-- Tabla de bitácora de acciones
CREATE TABLE bitacora (
  id_bitacora NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_usuario NUMBER(11) NOT NULL,
  id_aplicacion NUMBER(11) NOT NULL,
  fecha TIMESTAMP NOT NULL,
  ip VARCHAR2(45),
  accion VARCHAR2(50),
  nombre_pc VARCHAR2(50),
  CONSTRAINT fk_bitacora_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);



-- Crear tabla perfiles
CREATE TABLE perfiles (
    id_perfil NUMBER(10) PRIMARY KEY,
    nombre_perfil VARCHAR2(85),
    estatus_perfil CHAR(1)
);




--tabla aplicacion
CREATE TABLE aplicacion (
    id_aplicacion NUMBER(5) PRIMARY KEY,
    nombre_aplicacion VARCHAR2(25) NOT NULL,
    estatus_aplicacion CHAR(1) NOT NULL
);



-- Crear tabla relperfusu
CREATE TABLE relperfusu (
    id_usuario NUMBER(11) NOT NULL,
    id_perfil NUMBER(11) NOT NULL,

    -- Clave primaria compuesta
    CONSTRAINT pk_relperfusu PRIMARY KEY (id_usuario, id_perfil),

    -- Clave foránea hacia perfiles
    CONSTRAINT fk_perfil FOREIGN KEY (id_perfil)
        REFERENCES perfiles(id_perfil),

    -- Clave foránea hacia usuario
    CONSTRAINT fk_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
);



SELECT table_name FROM user_tables;--MUESTRA TABLAS CREADAS


--OBLIGATORIO COLOCARLO ASI usuario: admin contraseña:(admin123)
--hacer el insert sin modificar nada ya que es cifrado sha-256 y solo asi lo va reconocer
INSERT INTO usuario (username, password)
VALUES ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9');

COMMIT;

-- Insertar perfiles
INSERT INTO perfiles (id_perfil, nombre_perfil, estatus_perfil) VALUES (111, 'ADMINISTRADOR', '1');
INSERT INTO perfiles (id_perfil, nombre_perfil, estatus_perfil) VALUES (222, 'BIBLIOTECARIO', '1');
INSERT INTO perfiles (id_perfil, nombre_perfil, estatus_perfil) VALUES (333, 'USUARIOS', '1');

-- Confirmar cambios
COMMIT;

